name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
      - name: Install dependencies
        run: |
          sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-fonts-extra
          pip install sphinx sphinx_rtd_theme myst_parser rst2pdf sphinx-simplepdf
      - name: Sphinx build
        run: |
          sphinx-build docs _build
          sphinx-build -M simplepdf docs _build
          sphinx-build -M latexpdf docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true