# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches: [ "main" ]
    paths:
      - '**.tex'        # cualquier .tex en el repo
  pull_request:
    branches: [ "main" ]
    paths:
      - '**.tex'
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Install Pygments
        run: pip install Pygments
        
      - name: LaTeX compilation I
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: UPMSBM-CMSIS-RTOS.tex
          working_directory: presentation
          args: -pdf -shell-escape -f
          
      - name: LaTeX compilation II
        # You may pin to the exact commit or the version.
        # uses: dante-ev/latex-action@49cf7cb5f79e7b2006dbdffea85e02bec0b6244b
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: UPMSBM-CMSIS-RTOS_en.tex
          working_directory: presentation
          args: -pdf -shell-escape -f
      

          
      - uses: actions/upload-artifact@v4
        with:
          name: UPMSBM-CMSIS-RTOS.pdf
          path: presentation/UPMSBM-CMSIS-RTOS.pdf presentation/UPMSBM-CMSIS-RTOS_en.pdf
          
          
      - name: Delete Release
        run: |
          gh release delete 1.0 --cleanup-tag --yes || echo "Release 1.0 not found, skipping."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Release and Upload Assets
        run: |
          gh release create 1.0 \
            --title "1.0" \
            --notes "Release notes for 1.0: This presentation always contains the last version of the slides" \
            ./presentation/UPMSBM-CMSIS-RTOS.pdf \
            ./presentation/UPMSBM-CMSIS-RTOS_en.pdf
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
